@baseUrl = http://localhost:3000
@token = {{login.response.body.$.token}}

### server test
GET {{baseUrl}}/

### ------------ AUTH ------------
### Login
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "joaovictorgouveiar@gmail.com",
    "password": "password2"
}

### Register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "jotave@gmail.com",
    "name": "Jotave",
    "password": "123456"
}

### ------------ TASKS -----------
### All tasks (done & undone)
GET {{baseUrl}}/api/v1/task/all
Authorization: bearer {{token}}

### All tasks undone
GET {{baseUrl}}/api/v1/task/todo
Authorization: bearer {{token}}

### All tasks done
GET {{baseUrl}}/api/v1/task/done
Authorization: bearer {{token}}

### Specific task
GET {{baseUrl}}/api/v1/task/select/9
Authorization: bearer {{token}}

### Conclue task
PATCH {{baseUrl}}/api/v1/task/conclue/2
Authorization: bearer {{token}}

### Create Task
POST {{baseUrl}}/api/v1/task/create
Authorization: bearer {{token}}
Content-Type: application/json

{
    "category": "Pessoal",
    "title": "Do homework",
    "description": "Do the homework of the math class",
    "status": false,
    "taskDate": "2024-12-17T00:18:00.000Z",
    "todayDate": "2024-12-17T00:18:00.000Z",
    "maxDate": "2025-02-17T00:18:00.000Z", 
    "days": "3 4"
}

### Create Task simple
POST {{baseUrl}}/api/v1/task/create
Authorization: bearer {{token}}
Content-Type: application/json

{
    "category": "Pessoal",
    "title": "Do homework",
    "description": "Do the homework of the math class",
    "status": false,
    "taskDate": "2025-12-17T00:18:00.000Z",
    "todayDate": "2024-12-17T00:18:00.000Z",
    "maxDate": null, 
    "days": null
}